#Dockerfile_Risc0_2.3.1
#docker build . -t ghcr.io/curiousjaki/zkvm-base:latest --platform linux/amd64 -f Dockerfile_Risc0_2.3.1
FROM rust:1.86-bookworm AS builder
RUN curl -L https://risczero.com/install | bash
RUN ~/.risc0/bin/rzup install cargo-risczero 2.3.1
RUN ~/.risc0/bin/rzup install cpp 2024.1.5
RUN ~/.risc0/bin/rzup install r0vm 2.3.1
RUN ~/.risc0/bin/rzup install rust 1.88.0